### ISSUE TITLE
Cannot import name 'ConstantInputWarning' from 'scipy.stats' 

### ISSUE THREAD

**Issue by Harper19** [raw-lab/mercat2#4]
Hello, this tool looks great! But when running mercat2 using demo data, I encountered the following error:

File "/storage/home/hcoda1/1/kbian8/.conda/envs/mercat2/lib/python3.10/site-packages/skbio/stats/distance/_mantel.py", line 16, in <module>
    from scipy.stats import ConstantInputWarning
ImportError: cannot import name 'ConstantInputWarning' from 'scipy.stats' (/storage/home/hcoda1/1/kbian8/.conda/envs/mercat2/lib/python3.10/site-packages/scipy/stats/__init__.py)

SciPy has been updated to 1.8.1 and all dependencies have been installed as well as their version matched. 

No idea how to solve this. May I have your suggestions?

**Comment by decrevi** [comment]
Thank you for your feedback!

This sounds like a dependency version issue. 

I will need to check the version that I tested this with, it is possible that something broke with a new update of SciPy or one of its dependencies.

**Comment by decrevi** [comment]
After some digging I found the issue. When we published version 1.0 we were using scikit-bio=0.5.7 which has since been updated to 0.5.9. It looks like this is what is causing this error since both scikit-bio and scipy have had updates since our release.

During testing I also realized another dependency missing, ray-tune.
Here is a temporary fix while we publish a dependency fix to Bioconda.

To update a current installation activate your environment with MerCat2 and run this command:
`mamba install -c bioconda -c conda-forge scikit-bio=0.5.7 ray-tune`

To create a new environment use this command:
`mamba create -n mercat2 -c bioconda -c conda-forge mercat2=1.0 scikit-bio=0.5.7 ray-tune`

I also do recommend using mamba, I have noticed it is much faster and finds dependencies more accurately than using the 'conda' command directly.

We will publish a patch after a bit more testing to ensure the best versions of these and other dependencies are installed.

Please let me know if this works for you, or if you have any further issues,
-Jose

**Comment by Harper19** [comment]
Thank you for your prompt reply! This error has been solved by your solution!

However, when I run long read data from Nanopore, this error happened:

File "/storage/home/hcoda1/1/kbian8/.conda/envs/mercat2/lib/python3.10/site-packages/ray/_private/worker.py", line 2382, in get
    raise value
ray.exceptions.LocalRayletDiedError: The task's local raylet died. Check raylet.out for more information.

Is that due to the long reads? 

BTW, it seems like another topic. If needed, I can create another request to make the Q&A organized.

-Kaiqin

**Comment by raw-lab** [comment]
This is a Ray error. We have tested with nanopore data. Check you show us the raylet.out? Also, attach some lines of your file so we can check.

**Comment by decrevi** [comment]
Hello, I'm glad that first fix helped!
Yes, this is actually a different issue maybe we can move some of this to a new issue in case someone comes across it and it helps them...

That is an issue with Ray, I do believe it is once again a dependency issue. Sometimes on different machines the dependencies that are installed are of different versions depending on what is in your base system and version of Anaconda.

Please try this:
`mamba create -n mercat2 -c bioconda -c conda-forge mercat2=1.0 grpcio'=1.43' python">=3.9" scikit-bio=0.5.7 ray-tune`

**Comment by atred** [comment]
These issues should now be fixed in the latest release on bioconda.

**Comment by Harper19** [comment]
Thanks u guys so much!

**Comment by raw-lab** [comment]
You're very welcome. Thank you for using MerCat2. Let us know if you need anything? Or have other features you would like to see (options etc). 

We have a mamba install that is quite fast now:
mamba create -n mercat2 -c conda-forge -c bioconda mercat2
conda activate mercat2

Also, you can install with pip:
mamba create -n mercat2 
conda activate mercat2
pip install mercat2

Many thanks!
